"use client";

import { useEffect, useState } from "react";
import { ensurePushDevice } from "../../lib/push-client";

export default function NotificationSettings({onMessage,onEnabledChange}:{onMessage:(message:string)=>void;onEnabledChange?:(enabled:boolean)=>void}){
  const [enabled,setEnabled]=useState(true);const [configured,setConfigured]=useState(false);const [publicKey,setPublicKey]=useState("");const [permission,setPermission]=useState<NotificationPermission|"unsupported">("default");const [busy,setBusy]=useState(false);
  useEffect(()=>{const timer=window.setTimeout(()=>{setPermission(typeof Notification==="undefined"?"unsupported":Notification.permission);fetch("/api/notifications/settings").then(response=>response.json()).then((body:{enabled:boolean;configured:boolean;publicKey:string})=>{setEnabled(body.enabled);setConfigured(body.configured);setPublicKey(body.publicKey);onEnabledChange?.(body.enabled)}).catch(()=>undefined)},0);return()=>window.clearTimeout(timer)},[onEnabledChange]);
  const saveEnabled=async(value:boolean)=>{setEnabled(value);onEnabledChange?.(value);await fetch("/api/notifications/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:value})});if(!value&&"serviceWorker" in navigator){const registration=await navigator.serviceWorker.ready.catch(()=>null);const subscription=await registration?.pushManager.getSubscription();if(subscription){await fetch("/api/notifications/subscriptions",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:subscription.endpoint})});await subscription.unsubscribe()}}onMessage(value?"اعلان‌های سامانه فعال شد":"اعلان گوشی غیرفعال شد؛ اعلان‌های داخل برنامه باقی می‌مانند")};
  const activate=async()=>{if(!configured)return onMessage("کلید ارسال اعلان هنوز روی سرور تنظیم نشده است");if(!("serviceWorker" in navigator)||typeof Notification==="undefined")return onMessage("این مرورگر از اعلان گوشی پشتیبانی نمی‌کند");setBusy(true);try{const result=await Notification.requestPermission();setPermission(result);if(result!=="granted")throw new Error("اجازه اعلان داده نشد؛ از تنظیمات مرورگر آن را فعال کنید");await ensurePushDevice(publicKey);await saveEnabled(true);onMessage("اعلان مأموریت روی این دستگاه فعال شد")}catch(error){onMessage(error instanceof Error?error.message:"فعال‌سازی اعلان ناموفق بود")}finally{setBusy(false)}};
  const permissionLabel=permission==="granted"?"اجازه داده شده":permission==="denied"?"مسدود در مرورگر":permission==="unsupported"?"پشتیبانی نمی‌شود":"هنوز اجازه گرفته نشده";
  return <div className="notification-settings-card"><div className="settings-heading"><span>♧</span><div><h2>تنظیمات اعلان‌ها</h2><p>اعلان داخل برنامه همیشه قابل مشاهده است؛ اعلان گوشی را شما کنترل می‌کنید.</p></div></div><label className="settings-master-toggle" htmlFor="notification-master"><span><b>اعلان مأموریت‌ها</b><small>در حالت پیش‌فرض فعال است</small></span><input id="notification-master" aria-label="فعال بودن اعلان مأموریت‌ها" type="checkbox" checked={enabled} onChange={event=>saveEnabled(event.target.checked).catch(()=>onMessage("ذخیره تنظیم اعلان ناموفق بود"))}/></label><div className="permission-status"><span><small>وضعیت اجازه مرورگر</small><b>{permissionLabel}</b></span><i className={permission==="granted"?"good":""}>{permission==="granted"?"✓":"!"}</i></div><button className="primary-wide" onClick={activate} disabled={busy||!enabled}>{busy?"در حال فعال‌سازی...":permission==="granted"?"ثبت دوباره این دستگاه":"فعال‌سازی اعلان روی گوشی"}</button><p className="notification-help">برای دریافت اعلان، سایت باید با HTTPS باز شود. در آیفون، برنامه را به Home Screen اضافه کنید و سپس این دکمه را بزنید.</p></div>;
}
